<?php
return [
    'wine_category' => 'Category',
    'wine_appellation' => 'Appellation',
    'wine_variety' => 'Grape Variety',
    'wine_volume' => 'Volume',
    'wine_producer' => 'Producer',
    'wine_geography' => 'Geography',
    'wine_climate' => 'Climate',
    'wine_soil' => 'Soil',
    'wine_alcohol' => 'Alcohol',
    'wine_labels' => 'Labels',
    'follow-us-instagram' => 'Follow us on Instagram',
    'alcohol-message' => 'Message about alcohol consumption',
    'all-rights-reserved' => 'All Rights Reserved',
    'discover-wines' => 'Discover our wines',
    'see-more' => 'See more',
    'wines-url' => 'Link to page "our wines"',
    'find-a-store' => 'Find a store',
    'no-store-found' => 'No store found.',
    'privacy-policy' => 'Privacy Policy',
    'privacy-policy-link' => 'Link to privacy policy page',
    'no-wine-found' => 'No wine found in this category.',
];
?>
